In [50]:
x = 25
x

25

In [51]:
type(x)

int

In [52]:
y = 3

In [53]:
py_sum = x + y
py_sum

28

In [54]:
type(py_sum)

int

In [55]:
x_float = 25.0
float_sum = x_float + y
float_sum

28.0

In [56]:
type(float_sum)

float

Scalars in PyTorch

In [57]:
import torch

In [58]:
x_pt = torch.tensor(25) # type specification optional, e.g.: dtype=torch.float16
x_pt

tensor(25)

In [59]:
x_pt.shape

torch.Size([])

Scalars in Tensorflow

In [60]:
import tensorflow as tf

In [61]:
x_tf = tf.Variable(25, dtype=tf.int16) # dtype is optional
x_tf

<tf.Variable 'Variable:0' shape=() dtype=int16, numpy=25>

In [62]:
x_tf.shape

TensorShape([])

In [63]:
y_tf = tf.Variable(3, dtype=tf.int16)

In [64]:
x_tf + y_tf

<tf.Tensor: shape=(), dtype=int16, numpy=28>

In [65]:
tf_sum = tf.add(x_tf, y_tf)
tf_sum

<tf.Tensor: shape=(), dtype=int16, numpy=28>

In [66]:
tf_sum.numpy() # note that NumPy operations automatically convert tensors to NumPy arrays, and vice versa

28

In [67]:
type(tf_sum.numpy())

numpy.int16

In [68]:
tf_float = tf.Variable(25., dtype=tf.float16)
tf_float

<tf.Variable 'Variable:0' shape=() dtype=float16, numpy=25.0>

Vectors (Rank 1 Tensors) in NumPy

In [69]:
import numpy as np

x = np.array([25, 2, 5])
x

array([25,  2,  5])

In [70]:
len(x)

3

In [71]:
x.shape

(3,)

In [72]:
type(x)

numpy.ndarray

In [73]:
x[0]

25

In [74]:
type(x[0])

numpy.int64

Vector Transposition

In [75]:
# Transposing a regular 1-D array has no effect ....
x_t = x.T
x_t

array([25,  2,  5])

In [76]:
x_t.shape

(3,)

In [77]:
# ....but it does we use nested "matrix-style" brackets:
y = np.array([[25, 2, 5]])
y

array([[25,  2,  5]])

In [78]:
y.shape

(1, 3)

In [79]:
# ....but can transpose a matrix with a dimension of length 1, which is mathematically equivalent:
y_t = y.T
y_t

array([[25],
       [ 2],
       [ 5]])

In [80]:
y_t.shape # this is a column vector as it has 3 rows and 1 column

(3, 1)

In [81]:
# Column vector can be transposed back to original row vector:
y_t.T

array([[25,  2,  5]])

In [82]:
y_t.T.shape

(1, 3)

Zero Vectors

Have no effect if added to another vector

In [83]:
z = np.zeros(3)
z

array([0., 0., 0.])

Vectors in PyTorch and Tensorflow

In [84]:
x_pt = torch.tensor([25, 2, 5])
x_pt

tensor([25,  2,  5])

In [85]:
x_tf = tf.Variable([25, 2, 5])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([25,  2,  5], dtype=int32)>

L2 Norm

In [86]:
x

array([25,  2,  5])

In [87]:
(25**2 + 2**2 + 5**2)**(1/2)

25.573423705088842

In [88]:
np.linalg.norm(x)

25.573423705088842

So, if units in this 3-dimensional vector space are meters, then the vector x has a length of 25.6m

L1 Norm

In [89]:
x

array([25,  2,  5])

In [90]:
np.abs(25) + np.abs(2) + np.abs(5)

32

Squared L2 Norm

In [91]:
x

array([25,  2,  5])

In [92]:
(25**2 + 2**2 + 5**2)

654

In [93]:
# we'll cover tensor multiplication more soon but to prove point quickly:
np.dot(x, x)

654

Max Norm

In [94]:
x

array([25,  2,  5])

In [95]:
np.max([np.abs(25), np.abs(2), np.abs(5)])

25

Orthogonal Vectors

In [96]:
i = np.array([1, 0])
i

array([1, 0])

In [97]:
j = np.array([0, 1])
j

array([0, 1])

In [98]:
np.dot(i, j) # detail on the dot operation coming up.....

0

Matrices (Rank 2 Tensors) in NumPy

In [99]:
# Use array() with nested brackets
X = np.array([[25, 2], [5, 26], [3, 7]])
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [100]:
X.shape

(3, 2)

In [101]:
X.size

6

In [102]:
# Select left column of matrix X (zero-indexed)
X[:,0]

array([25,  5,  3])

In [104]:
# Select middle row of matrix X
X[1,:]

array([3, 7])

In [110]:
# Another slicing-by-index example
X[0:2, 0:2]

array([[25,  2],
       [ 5, 26]])

Matrices in PyTorch

In [111]:
X_pt = torch.tensor([[25, 2], [5, 26], [3, 7]])
X_pt

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [112]:
X_pt.shape # more pythonic

torch.Size([3, 2])

In [115]:
X_pt[1,:]

tensor([ 5, 26])

Matrices in TensorFlow

In [116]:
X_tf = tf.Variable([[25, 2], [5, 26], [3, 7]])
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[25,  2],
       [ 5, 26],
       [ 3,  7]], dtype=int32)>

In [117]:
tf.rank(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [118]:
tf.shape(X_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2], dtype=int32)>

In [119]:
X_tf[1,:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 5, 26], dtype=int32)>

Higher-Rank Tensors

As an example, rank 4 tensors are common for images, where each dimension corresponds to:
1. Number of images in training batch, e.g., 32
2. Image height in pixels, e.g., 28 for [MNIST digits](http://yann.lecun.com/exdb/mnist/)
3. Image width in pixels, e.g., 28
4. Number of color channels, e.g., 3 for full-color images (RGB)

In [120]:
images_pt = torch.zeros([32, 28, 28, 3])

In [ ]:
# images_pt

In [ ]:
images_tf = tf.zeros([32, 28, 28, 3])

In [ ]:
# images_tf