In [2]:
x = 25
x

25

In [3]:
type(x)

int

In [4]:
y = 3

In [5]:
py_sum = x + y
py_sum

28

In [6]:
type(py_sum)

int

In [7]:
x_float = 25.0
float_sum = x_float + y
float_sum

28.0

In [8]:
type(float_sum)

float

Scalars in PyTorch

In [9]:
import torch

In [10]:
x_pt = torch.tensor(25) # type specification optional, e.g.: dtype=torch.float16
x_pt

tensor(25)

In [11]:
x_pt.shape

torch.Size([])

Scalars in Tensorflow

In [12]:
import tensorflow as tf

In [13]:
x_tf = tf.Variable(25, dtype=tf.int16) # dtype is optional
x_tf

<tf.Variable 'Variable:0' shape=() dtype=int16, numpy=25>

In [14]:
x_tf.shape

TensorShape([])

In [15]:
y_tf = tf.Variable(3, dtype=tf.int16)

In [16]:
x_tf + y_tf

<tf.Tensor: shape=(), dtype=int16, numpy=28>

In [17]:
tf_sum = tf.add(x_tf, y_tf)
tf_sum

<tf.Tensor: shape=(), dtype=int16, numpy=28>

In [18]:
tf_sum.numpy() # note that NumPy operations automatically convert tensors to NumPy arrays, and vice versa

28

In [19]:
type(tf_sum.numpy())

numpy.int16

In [20]:
tf_float = tf.Variable(25., dtype=tf.float16)
tf_float

<tf.Variable 'Variable:0' shape=() dtype=float16, numpy=25.0>

Vectors (Rank 1 Tensors) in NumPy

In [21]:
import numpy as np

x = np.array([25, 2, 5])
x

array([25,  2,  5])

In [22]:
len(x)

3

In [23]:
x.shape

(3,)

In [24]:
type(x)

numpy.ndarray

In [25]:
x[0]

25

In [26]:
type(x[0])

numpy.int64

Vector Transposition

In [27]:
# Transposing a regular 1-D array has no effect ....
x_t = x.T
x_t

array([25,  2,  5])

In [28]:
x_t.shape

(3,)

In [29]:
# ....but it does we use nested "matrix-style" brackets:
y = np.array([[25, 2, 5]])
y

array([[25,  2,  5]])

In [30]:
y.shape

(1, 3)

In [31]:
# ....but can transpose a matrix with a dimension of length 1, which is mathematically equivalent:
y_t = y.T
y_t

array([[25],
       [ 2],
       [ 5]])

In [32]:
y_t.shape # this is a column vector as it has 3 rows and 1 column

(3, 1)

In [33]:
# Column vector can be transposed back to original row vector:
y_t.T

array([[25,  2,  5]])

In [34]:
y_t.T.shape

(1, 3)

Zero Vectors

Have no effect if added to another vector

In [35]:
z = np.zeros(3)
z

array([0., 0., 0.])

Vectors in PyTorch and Tensorflow

In [36]:
x_pt = torch.tensor([25, 2, 5])
x_pt

tensor([25,  2,  5])

In [37]:
x_tf = tf.Variable([25, 2, 5])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([25,  2,  5], dtype=int32)>

L2 Norm

In [38]:
x

array([25,  2,  5])

In [39]:
(25**2 + 2**2 + 5**2)**(1/2)

25.573423705088842

In [40]:
np.linalg.norm(x)

25.573423705088842

So, if units in this 3-dimensional vector space are meters, then the vector x has a length of 25.6m

L1 Norm

In [41]:
x

array([25,  2,  5])

In [42]:
np.abs(25) + np.abs(2) + np.abs(5)

32

Squared L2 Norm

In [43]:
x

array([25,  2,  5])

In [44]:
(25**2 + 2**2 + 5**2)

654

In [45]:
# we'll cover tensor multiplication more soon but to prove point quickly:
np.dot(x, x)

654

Max Norm

In [46]:
x

array([25,  2,  5])

In [47]:
np.max([np.abs(25), np.abs(2), np.abs(5)])

25